### ISSUE TITLE
Make firefox-original.svg the default Firefox icon

### ISSUE THREAD

**Issue by leap0x7b** [Ashwatthaamaa/Neuwaita#22]
guy believed oversimplified firefox logo memes is real 🗿

**Comment by Ashwatthaamaa** [comment]
Sorry I can't do this change as I personally use the brand logo as firefox logo and I have my icon folder synced with git so it will always be like that. Also I have provided the alternate icons in the extras folder and you can use that. I know you don't like it but this is my personal preference, so hope you understand. thanks :)

**Comment by leap0x7b** [comment]
very bruh moment 🗿
